# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalyseWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnalyseWindow(object):
    def setupUi(self, AnalyseWindow):
        AnalyseWindow.setObjectName("AnalyseWindow")
        AnalyseWindow.resize(376, 180)
        self.centralwidget = QtWidgets.QWidget(AnalyseWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 351, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_set_file = QtWidgets.QPushButton(self.frame)
        self.button_set_file.setObjectName("button_set_file")
        self.gridLayout.addWidget(self.button_set_file, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_state = QtWidgets.QLabel(self.frame)
        self.label_state.setMinimumSize(QtCore.QSize(20, 0))
        self.label_state.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_state.setObjectName("label_state")
        self.gridLayout.addWidget(self.label_state, 0, 2, 1, 1)
        self.calctype = QtWidgets.QListWidget(self.frame)
        self.calctype.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.calctype.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.calctype.setObjectName("calctype")
        item = QtWidgets.QListWidgetItem()
        self.calctype.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.calctype.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.calctype.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.calctype.addItem(item)
        self.gridLayout.addWidget(self.calctype, 1, 0, 1, 1)
        self.calc_files = QtWidgets.QListWidget(self.frame)
        self.calc_files.setObjectName("calc_files")
        self.gridLayout.addWidget(self.calc_files, 1, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        AnalyseWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AnalyseWindow)
        QtCore.QMetaObject.connectSlotsByName(AnalyseWindow)

    def retranslateUi(self, AnalyseWindow):
        _translate = QtCore.QCoreApplication.translate
        AnalyseWindow.setWindowTitle(_translate("AnalyseWindow", "MainWindow"))
        self.button_set_file.setText(_translate("AnalyseWindow", "Set"))
        self.label.setText(_translate("AnalyseWindow", "Included Calculation file(s) state"))
        self.label_state.setText(_translate("AnalyseWindow", "1"))
        __sortingEnabled = self.calctype.isSortingEnabled()
        self.calctype.setSortingEnabled(False)
        item = self.calctype.item(0)
        item.setText(_translate("AnalyseWindow", "Main:"))
        item = self.calctype.item(1)
        item.setText(_translate("AnalyseWindow", "Frequency:"))
        item = self.calctype.item(2)
        item.setText(_translate("AnalyseWindow", "Solvent:"))
        item = self.calctype.item(3)
        item.setText(_translate("AnalyseWindow", "Big basis:"))
        self.calctype.setSortingEnabled(__sortingEnabled)
