# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnyPlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnyPlotter(object):
    def setupUi(self, AnyPlotter):
        AnyPlotter.setObjectName("AnyPlotter")
        AnyPlotter.resize(395, 338)
        AnyPlotter.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(AnyPlotter)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.spinBox_rows = QtWidgets.QSpinBox(self.frame)
        self.spinBox_rows.setMaximum(99999)
        self.spinBox_rows.setProperty("value", 3)
        self.spinBox_rows.setObjectName("spinBox_rows")
        self.gridLayout_2.addWidget(self.spinBox_rows, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox_columns = QtWidgets.QSpinBox(self.frame)
        self.spinBox_columns.setMaximum(99999)
        self.spinBox_columns.setProperty("value", 1)
        self.spinBox_columns.setObjectName("spinBox_columns")
        self.gridLayout_2.addWidget(self.spinBox_columns, 0, 3, 1, 1)
        self.button_set_rows_columns = QtWidgets.QPushButton(self.frame)
        self.button_set_rows_columns.setMinimumSize(QtCore.QSize(50, 0))
        self.button_set_rows_columns.setMaximumSize(QtCore.QSize(50, 16777215))
        self.button_set_rows_columns.setObjectName("button_set_rows_columns")
        self.gridLayout_2.addWidget(self.button_set_rows_columns, 0, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(21)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 3)
        self.plot_type = QtWidgets.QComboBox(self.frame)
        self.plot_type.setMinimumSize(QtCore.QSize(150, 0))
        self.plot_type.setObjectName("plot_type")
        self.plot_type.addItem("")
        self.plot_type.addItem("")
        self.gridLayout.addWidget(self.plot_type, 1, 0, 1, 1)
        self.checkBox_style = QtWidgets.QCheckBox(self.frame)
        self.checkBox_style.setStyleSheet("QCheckBox::indicator:checked {image: url(:/24x24/resources/icons/toggle_on.png);}\n"
"\n"
"QCheckBox::indicator:unchecked {image: url(:/24x24/resources/icons/toggle_off.png);}\n"
"")
        self.checkBox_style.setIconSize(QtCore.QSize(24, 24))
        self.checkBox_style.setCheckable(True)
        self.checkBox_style.setTristate(False)
        self.checkBox_style.setObjectName("checkBox_style")
        self.gridLayout.addWidget(self.checkBox_style, 1, 1, 1, 1)
        self.button_plot = QtWidgets.QPushButton(self.frame)
        self.button_plot.setObjectName("button_plot")
        self.gridLayout.addWidget(self.button_plot, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.frame)
        AnyPlotter.setCentralWidget(self.centralwidget)

        self.retranslateUi(AnyPlotter)
        QtCore.QMetaObject.connectSlotsByName(AnyPlotter)

    def retranslateUi(self, AnyPlotter):
        _translate = QtCore.QCoreApplication.translate
        AnyPlotter.setWindowTitle(_translate("AnyPlotter", "MainWindow"))
        self.label_2.setText(_translate("AnyPlotter", "Columns:"))
        self.label_3.setText(_translate("AnyPlotter", "Rows"))
        self.button_set_rows_columns.setText(_translate("AnyPlotter", "SET"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("AnyPlotter", "Colour"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("AnyPlotter", "Title(s)"))
        self.plot_type.setItemText(0, _translate("AnyPlotter", "Energy diagram"))
        self.plot_type.setItemText(1, _translate("AnyPlotter", "Line"))
        self.checkBox_style.setText(_translate("AnyPlotter", "Style"))
        self.button_plot.setText(_translate("AnyPlotter", "Plot"))
#import icons_rc
