# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalcSetupMeny.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setupMeny(object):
    def setupUi(self, setupMeny):
        setupMeny.setObjectName("setupMeny")
        setupMeny.resize(161, 161)
        setupMeny.setMinimumSize(QtCore.QSize(161, 161))
        setupMeny.setMaximumSize(QtCore.QSize(161, 161))
        setupMeny.setWindowOpacity(1.0)
        setupMeny.setStyleSheet("QMainWindow{\n"
"}\n"
"\n"
"QFrame {\n"
"/*background-color: rgb(56,58,89);*/\n"
"background-color: rgba(0,0,0,0.5);\n"
"/*border: 2px solid rgb(220,220,220);*/\n"
"/*border: 2px solid rgb(143, 23, 119);*/\n"
"border: 2px solid rgb(98, 114, 164);\n"
"/*border: 2px solid rgb(56,58,89);*/\n"
"\n"
"border-radius:10px;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"    /*background-color:rgb(98, 114, 164);*/\n"
"    background-color: rgb(220,220,220);\n"
"    color: rgb(143,23,119);\n"
"border-radius:10px;\n"
"\n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background-color: rgb(40, 40, 40);\n"
"    /*color:rgb(20,20,20);*/\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: rgb(143,23,119);\n"
"\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(143, 23, 119);\n"
"    background-color: rgb(20, 20, 20);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(setupMeny)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 161, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.R_button = QtWidgets.QPushButton(self.frame)
        self.R_button.setGeometry(QtCore.QRect(60, 20, 40, 40))
        self.R_button.setMinimumSize(QtCore.QSize(40, 40))
        self.R_button.setMaximumSize(QtCore.QSize(40, 40))
        self.R_button.setObjectName("R_button")
        self.Z_button = QtWidgets.QPushButton(self.frame)
        self.Z_button.setGeometry(QtCore.QRect(60, 100, 40, 40))
        self.Z_button.setMinimumSize(QtCore.QSize(40, 40))
        self.Z_button.setMaximumSize(QtCore.QSize(40, 40))
        self.Z_button.setObjectName("Z_button")
        self.P_button = QtWidgets.QPushButton(self.frame)
        self.P_button.setGeometry(QtCore.QRect(20, 60, 40, 40))
        self.P_button.setMinimumSize(QtCore.QSize(40, 40))
        self.P_button.setMaximumSize(QtCore.QSize(40, 40))
        self.P_button.setObjectName("P_button")
        self.X_button = QtWidgets.QPushButton(self.frame)
        self.X_button.setGeometry(QtCore.QRect(100, 60, 40, 40))
        self.X_button.setMinimumSize(QtCore.QSize(40, 40))
        self.X_button.setMaximumSize(QtCore.QSize(40, 40))
        self.X_button.setObjectName("X_button")
        self.button_pymol = QtWidgets.QPushButton(self.frame)
        self.button_pymol.setGeometry(QtCore.QRect(60, 60, 40, 40))
        self.button_pymol.setMinimumSize(QtCore.QSize(40, 40))
        self.button_pymol.setMaximumSize(QtCore.QSize(40, 40))
        self.button_pymol.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"background:transparent;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background:transparent;\n"
"    /*color:rgb(20,20,20);*/\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: rgb(143,23,119);\n"
"\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(143, 23, 119);\n"
"    background-color: rgb(20, 20, 20);\n"
"}\n"
"\n"
"")
        self.button_pymol.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/24x24/resources/icons/24px-PyMOL_logo_trans.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_pymol.setIcon(icon)
        self.button_pymol.setIconSize(QtCore.QSize(24, 24))
        self.button_pymol.setFlat(True)
        self.button_pymol.setObjectName("button_pymol")
        setupMeny.setCentralWidget(self.centralwidget)

        self.retranslateUi(setupMeny)
        QtCore.QMetaObject.connectSlotsByName(setupMeny)

    def retranslateUi(self, setupMeny):
        _translate = QtCore.QCoreApplication.translate
        setupMeny.setWindowTitle(_translate("setupMeny", "MainWindow"))
        self.R_button.setText(_translate("setupMeny", "R"))
        self.Z_button.setText(_translate("setupMeny", "Z"))
        self.P_button.setText(_translate("setupMeny", "P"))
        self.X_button.setText(_translate("setupMeny", "?"))
