# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileEditorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileEditorWindow(object):
    def setupUi(self, FileEditorWindow):
        FileEditorWindow.setObjectName("FileEditorWindow")
        FileEditorWindow.resize(524, 390)
        self.centralwidget = QtWidgets.QWidget(FileEditorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(500, 300))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.FileEditorBox = QtWidgets.QTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileEditorBox.sizePolicy().hasHeightForWidth())
        self.FileEditorBox.setSizePolicy(sizePolicy)
        self.FileEditorBox.setMinimumSize(QtCore.QSize(0, 0))
        self.FileEditorBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FileEditorBox.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.FileEditorBox.setObjectName("FileEditorBox")
        self.gridLayout_2.addWidget(self.FileEditorBox, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(305, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.OK_button = QtWidgets.QPushButton(self.frame)
        self.OK_button.setObjectName("OK_button")
        self.gridLayout.addWidget(self.OK_button, 0, 1, 1, 1)
        self.Cancel_button = QtWidgets.QPushButton(self.frame)
        self.Cancel_button.setObjectName("Cancel_button")
        self.gridLayout.addWidget(self.Cancel_button, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        FileEditorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FileEditorWindow)
        QtCore.QMetaObject.connectSlotsByName(FileEditorWindow)

    def retranslateUi(self, FileEditorWindow):
        _translate = QtCore.QCoreApplication.translate
        FileEditorWindow.setWindowTitle(_translate("FileEditorWindow", "MainWindow"))
        self.OK_button.setText(_translate("FileEditorWindow", "OK"))
        self.Cancel_button.setText(_translate("FileEditorWindow", "Cancel"))
